In [196]:
import numpy as np
import pandas as pd
import datetime as dt
from simpledbf import Dbf5
from datetime import date

In [3]:
dbf = Dbf5('E:/Windows 7 Backup_Sep18/Drive F_2018/Upwork Projects/2019/North America/USA/MAYA/opioids_july2013_june2014_export.dbf')

df = dbf.to_dataframe()

In [4]:
df2=df.groupby(['DE_ID','VENDOR'],axis =0)

In [72]:
pd.DataFrame(data=df2).head()

,DE_ID,VENDOR,DISP_DATE,SDATE,YYYYMMDD,PRESCRIBER,AMT_PAID,NDC,QTY,DAYS,GENDER,AGE,LN,AHFS,GCN_SEQNO
0,10478,250066,2013196,16755,20130715,J4538,14.25,603388721,60.0,15,F,51,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623
1,10478,250066,2013261,16820,20130918,K3626,14.25,603388721,60.0,15,F,51,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623
2,10478,250066,2014023,16947,20140123,K3626,9.92,603388721,40.0,20,F,51,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623
3,10478,466545,2014073,16997,20140314,28651,3.25,603233832,12.0,2,F,52,ACETAMINOPHEN-COD #3 TABLET,28080881,4165
4,10478,466545,2014086,17010,20140327,28624,3.25,603233832,12.0,2,F,52,ACETAMINOPHEN-COD #3 TABLET,28080881,4165

In [73]:
df2 = df.rename(columns = {"YYYYMMDD": "Date"})

In [75]:
df2.describe()

,DE_ID,DISP_DATE,SDATE,Date,AMT_PAID,NDC,QTY,DAYS,AGE
count,1.560174e+06,1.560174e+06,1.560174e+06,1.560174e+06,1.560174e+06,1.560174e+06,1.560174e+06,1.560174e+06,1.560174e+06
mean,4.644133e+05,2.013648e+06,1.691615e+04,2.013527e+07,2.046401e+01,1.613576e+10,6.513738e+01,1.579601e+01,4.110077e+01
std,3.494653e+05,4.116095e+02,1.055712e+02,4.690250e+03,1.247816e+02,2.647938e+10,5.275548e+01,1.165312e+01,1.591283e+01
min,1.047800e+04,2.013182e+06,1.674100e+04,2.013070e+07,0.000000e+00,2.403350e+07,2.000000e-01,1.000000e+00,0.000000e+00
25%,1.318485e+05,2.013267e+06,1.682600e+04,2.013092e+07,4.240000e+00,4.060367e+08,3.000000e+01,5.000000e+00,2.800000e+01
50%,4.085450e+05,2.013347e+06,1.690600e+04,2.013121e+07,7.690000e+00,6.031021e+08,6.000000e+01,1.300000e+01,4.400000e+01
75%,7.885082e+05,2.014085e+06,1.700900e+04,2.014033e+07,1.561000e+01,4.285808e+10,9.000000e+01,3.000000e+01,5.500000e+01
max,1.131288e+06,2.014181e+06,1.710500e+04,2.014063e+07,1.956799e+04,6.846202e+10,2.700000e+03,1.800000e+02,1.020000e+02

In [51]:
import csv
df2.to_csv('E:\\df.csv')

In [45]:
df2.AMT_PAID

0    14.25
1    14.25
2     9.92
3     3.25
4     3.25
Name: AMT_PAID, dtype: float64

In [46]:
df2.isna().sum()

DE_ID         0
VENDOR        0
DISP_DATE     0
SDATE         0
YYYYMMDD      0
PRESCRIBER    0
AMT_PAID      0
NDC           0
QTY           0
DAYS          0
GENDER        0
AGE           0
LN            0
AHFS          0
GCN_SEQNO     0
dtype: int64

In [47]:
df.isnull().sum()

DE_ID             0
VENDOR            0
DISP_DATE         0
SDATE             0
YYYYMMDD          0
PRESCRIBER    68000
AMT_PAID          0
NDC               0
QTY               0
DAYS              0
GENDER            0
AGE               0
LN                0
AHFS              0
GCN_SEQNO         0
dtype: int64

In [48]:
df.count()

DE_ID         1560174
VENDOR        1560174
DISP_DATE     1560174
SDATE         1560174
YYYYMMDD      1560174
PRESCRIBER    1492174
AMT_PAID      1560174
NDC           1560174
QTY           1560174
DAYS          1560174
GENDER        1560174
AGE           1560174
LN            1560174
AHFS          1560174
GCN_SEQNO     1560174
dtype: int64

In [115]:
df_QL = df.groupby('DE_ID').count()

In [116]:
df_QL['TF'] = df_QL['AMT_PAID']>=4

In [117]:
pd.DataFrame(data=df_QL).head()

,VENDOR,DISP_DATE,SDATE,YYYYMMDD,PRESCRIBER,AMT_PAID,NDC,QTY,DAYS,GENDER,AGE,LN,AHFS,GCN_SEQNO,TF
DE_ID,,,,,,,,,,,,,,,
10478,6,6,6,6,6,6,6,6,6,6,6,6,6,6,True
10479,8,8,8,8,8,8,8,8,8,8,8,8,8,8,True
10480,13,13,13,13,13,13,13,13,13,13,13,13,13,13,True
10485,1,1,1,1,1,1,1,1,1,1,1,1,1,1,False
10488,1,1,1,1,1,1,1,1,1,1,1,1,1,1,False

In [127]:
pd.Series(df_QL['TF']).value_counts()

False    348921
True      84899
Name: TF, dtype: int64

In [ ]:
pivot_df = pd.pivot(df,columns=['','','','',])

In [76]:
# before merging we need to determine px that are continuously enrlled
# so for each year px that had at least one claim in each quater

In [84]:
import datetime
x = datetime.datetime.today()
print(x.strftime("%b %d %Y %H:%M:%S"))

May 28 2019 13:54:58

In [241]:
def get_datetime(Date):
    date_string = str(Date)
    my_dict = {}
    my_dict['year'] = date_string[:4] 
    my_dict['month'] = date_string[4:6]
    my_dict['day'] = date_string[6:8]
    return my_dict['day']

In [242]:

my_date = 20120530
mydate_dict = get_datetime(my_date)

In [243]:
print(mydate_dict)

30

In [244]:
df2['Day'] = 0
df2['Month'] = 0
df2['Year'] = 0

In [245]:
df2['Day'] = get_datetime(df2.Date)

In [254]:
df2["New_Date"] = pd.to_datetime(df2["Date"],format = '%Y-%m-%d')

In [251]:
df2

,DE_ID,VENDOR,DISP_DATE,SDATE,Date,PRESCRIBER,AMT_PAID,NDC,QTY,DAYS,GENDER,AGE,LN,AHFS,GCN_SEQNO,var,Month,Day,Year,New_Date
0,10478,250066,2013196,16755,20130715,J4538,14.25,603388721,60.0,15,F,51,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20130715,0,,0,1970-01-01 00:00:00.020130715
1,10478,250066,2013261,16820,20130918,K3626,14.25,603388721,60.0,15,F,51,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20130918,0,,0,1970-01-01 00:00:00.020130918
2,10478,250066,2014023,16947,20140123,K3626,9.92,603388721,40.0,20,F,51,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140123,0,,0,1970-01-01 00:00:00.020140123
3,10478,466545,2014073,16997,20140314,28651,3.25,603233832,12.0,2,F,52,ACETAMINOPHEN-COD #3 TABLET,28080881,4165,20140314,0,,0,1970-01-01 00:00:00.020140314
4,10478,466545,2014086,17010,20140327,28624,3.25,603233832,12.0,2,F,52,ACETAMINOPHEN-COD #3 TABLET,28080881,4165,20140327,0,,0,1970-01-01 00:00:00.020140327
5,10478,250066,2014091,17015,20140401,N1529,6.69,603388721,35.0,6,F,52,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140401,0,,0,1970-01-01 00:00:00.020140401
6,10479,466045,2013182,16741,20130701,E4159,86.03,591093201,360.0,45,F,48,OXYCODONE-ACETAMINOPHEN 10-325,28080913,48977,20130701,0,,0,1970-01-01 00:00:00.020130701
7,10479,466045,2013182,16741,20130701,E4159,102.92,42858030301,180.0,30,F,48,HYDROMORPHONE 8 MG TABLET,28080900,15190,20130701,0,,0,1970-01-01 00:00:00.020130701
8,10479,466906,2013227,16786,20130815,H8135,146.95,406324901,180.0,30,F,48,HYDROMORPHONE 8 MG TABLET,28080900,15190,20130815,0,,0,1970-01-01 00:00:00.020130815
9,10479,466906,2013227,16786,20130815,H8135,176.75,47781023001,240.0,30,F,48,OXYCODONE-ACETAMINOPHEN 10-325,28080913,48977,20130815,0,,0,1970-01-01 00:00:00.020130815
10,10479,466045,2013252,16811,20130909,E4159,102.92,42858030301,180.0,20,F,48,HYDROMORPHONE 8 MG TABLET,28080900,15190,20130909,0,,0,1970-01-01 00:00:00.020130909
11,10479,462755,2013253,16812,20130910,E4159,149.10,591093201,360.0,30,F,48,OXYCODONE-ACETAMINOPHEN 10-325,28080913,48977,20130910,0,,0,1970-01-01 00:00:00.020130910
12,10479,462755,2013291,16850,20131018,E4159,19.58,591074905,240.0,30,F,48,OXYCODONE-ACETAMINOPHEN 5-325,28080802,4222,20131018,0,,0,1970-01-01 00:00:00.020131018
13,10479,466045,2013291,16850,20131018,E4159,70.82,42858030301,120.0,30,F,48,HYDROMORPHONE 8 MG TABLET,28080900,15190,20131018,0,,0,1970-01-01 00:00:00.020131018
14,10480,465032,2013237,16796,20130825,P5169,4.16,57664037713,60.0,30,F,45,TRAMADOL HCL 50 MG TABLET,28080840,23139,20130825,0,,0,1970-01-01 00:00:00.020130825
15,10480,465032,2013266,16825,20130923,P5169,4.16,57664037713,60.0,30,F,45,TRAMADOL HCL 50 MG TABLET,28080840,23139,20130923,0,,0,1970-01-01 00:00:00.020130923
16,10480,465032,2013294,16853,20131021,P5169,4.16,57664037713,60.0,30,F,45,TRAMADOL HCL 50 MG TABLET,28080840,23139,20131021,0,,0,1970-01-01 00:00:00.020131021
17,10480,144770,2013331,16890,20131127,M5113,5.62,65162062711,90.0,23,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20131127,0,,0,1970-01-01 00:00:00.020131127
18,10480,144770,2013348,16907,20131214,M5113,5.62,65162062711,90.0,23,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20131214,0,,0,1970-01-01 00:00:00.020131214
19,10480,144770,2013348,16907,20131214,M5113,5.62,65162062711,90.0,23,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20131214,0,,0,1970-01-01 00:00:00.020131214
20,10480,465032,2014014,16938,20140114,K0839,5.62,57664037713,90.0,12,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140114,0,,0,1970-01-01 00:00:00.020140114
21,10480,465032,2014034,16958,20140203,K0839,5.62,57664037713,90.0,12,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140203,0,,0,1970-01-01 00:00:00.020140203
22,10480,144974,2014065,16989,20140306,PA074,3.72,57664037718,120.0,30,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140306,0,,0,1970-01-01 00:00:00.020140306
23,10480,465032,2014097,17021,20140407,M5113,3.64,57664037713,120.0,30,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140407,0,,0,1970-01-01 00:00:00.020140407
24,10480,465032,2014121,17045,20140501,M5113,3.04,57664037713,90.0,12,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140501,0,,0,1970-01-01 00:00:00.020140501
25,10480,465032,2014149,17073,20140529,M5113,3.64,57664037718,120.0,30,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140529,0,,0,1970-01-01 00:00:00.020140529
26,10480,465032,2014176,17100,20140625,ANP69,3.04,57664037718,90.0,30,F,46,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140625,0,,0,1970-01-01 00:00:00.020140625
27,10485,462524,2014106,17030,20140416,N3341,3.11,406036705,12.0,3,F,44,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140416,0,,0,1970-01-01 00:00:00.020140416
28,10488,144181,2013183,16742,20130702,K1627,11.71,53746010901,60.0,20,F,55,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20130702,0,,0,1970-01-01 00:00:00.020130702
29,10489,145410,2013183,16742,20130702,J7963,14.11,591038505,150.0,25,M,43,HYDROCODON-ACETAMINOPH 7.5-500,28080818,4205,20130702,0,,0,1970-01-01 00:00:00.020130702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560144,1129782,462274,2014178,17102,20140627,P0629,7.05,591320205,15.0,2,M,56,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140627,0,,0,1970-01-01 00:00:00.020140627
1560145,1129799,466144,2014181,17105,20140630,ANP43,7.25,68382031910,56.0,14,M,34,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140630,0,,0,1970-01-01 00:00:00.020140630
1560146,1129886,466925,2014176,17100,20140625,ANP61,14.32,406036505,30.0,5,F,56,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140625,0,,0,1970-01-01 00:00:00.020140625
1560147,1129906,465972,2014178,17102,20140627,M8502,7.73,65162062711,12.0,4,M,18,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140627,0,,0,1970-01-01 00:00:00.020140627
1560148,1129928,465807,2014171,17095,20140620,M1910,12.64,603389028,40.0,5,F,31,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140620,0,,0,1970-01-01 00:00:00.020140620
1560149,1129949,464181,2014167,17091,20140616,PA064,9.51,591260505,14.0,7,F,21,HYDROCODON-ACETAMINOPH 7.5-325,28080798,47431,20140616,0,,0,1970-01-01 00:00:00.020140616
1560150,1129969,462278,2014179,17103,20140628,L4252,12.31,591261205,30.0,7,F,31,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140628,0,,0,1970-01-01 00:00:00.020140628
1560151,1129990,464640,2014162,17086,20140611,H2154,366.58,59011043010,56.0,28,F,33,OXYCONTIN 30 MG TABLET,28081217,63516,20140611,0,,0,1970-01-01 00:00:00.020140611
1560152,1130050,464041,2014170,17094,20140619,K2112,12.81,591260505,30.0,7,F,27,HYDROCODON-ACETAMINOPH 7.5-325,28080798,47431,20140619,0,,0,1970-01-01 00:00:00.020140619
1560153,1130050,464041,2014177,17101,20140626,K2112,12.81,591260505,30.0,7,F,27,HYDROCODON-ACETAMINOPH 7.5-325,28080798,47431,20140626,0,,0,1970-01-01 00:00:00.020140626
1560154,1130070,462968,2014181,17105,20140630,ANP81,26.80,406036705,80.0,27,F,49,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140630,0,,0,1970-01-01 00:00:00.020140630
1560155,1130182,462541,2014172,17096,20140621,L7925,7.20,591320205,20.0,3,F,21,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140621,0,,0,1970-01-01 00:00:00.020140621
1560156,1130188,466926,2014178,17102,20140627,J7063,17.64,65162062711,120.0,30,M,38,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140627,0,,0,1970-01-01 00:00:00.020140627
1560157,1130272,142204,2014175,17099,20140624,E7871,12.28,65162062711,60.0,10,F,38,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140624,0,,0,1970-01-01 00:00:00.020140624
1560158,1130304,465140,2014170,17094,20140619,M8496,8.01,378415105,60.0,15,F,70,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140619,0,,0,1970-01-01 00:00:00.020140619
1560159,1130308,145749,2014178,17102,20140627,PA083,8.60,591320205,30.0,3,M,16,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140627,0,,0,1970-01-01 00:00:00.020140627
1560160,1130348,320271,2014164,17088,20140613,D4239,16.01,603388732,60.0,15,F,42,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140613,0,,0,1970-01-01 00:00:00.020140613
1560161,1130348,320271,2014179,17103,20140628,D4239,16.01,603388732,60.0,15,F,42,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140628,0,,0,1970-01-01 00:00:00.020140628
1560162,1130350,465680,2014176,17100,20140625,N0420,9.63,603389028,20.0,5,M,59,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140625,0,,0,1970-01-01 00:00:00.020140625
1560163,1130350,465680,2014181,17105,20140630,M6291,14.89,65162062711,90.0,15,M,59,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140630,0,,0,1970-01-01 00:00:00.020140630
1560164,1130408,145591,2014170,17094,20140619,K0723,10.42,406575501,120.0,30,M,58,METHADONE HCL 5 MG TABLET,28080903,4242,20140619,0,,0,1970-01-01 00:00:00.020140619
1560165,1130425,464777,2014173,17097,20140622,M3033,7.29,68382031910,60.0,30,M,34,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140622,0,,0,1970-01-01 00:00:00.020140622
1560166,1130429,466951,2014176,17100,20140625,PA061,9.97,57664037718,60.0,15,M,36,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140625,0,,0,1970-01-01 00:00:00.020140625
1560167,1130530,465339,2014173,17097,20140622,M0251,7.20,591320205,20.0,3,M,65,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140622,0,,0,1970-01-01 00:00:00.020140622
1560168,1130533,465979,2014176,17100,20140625,M6692,11.13,603389028,30.0,3,F,52,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140625,0,,0,1970-01-01 00:00:00.020140625
1560169,1130579,462650,2014175,17099,20140624,PA045,4.00,378415105,20.0,3,M,51,TRAMADOL HCL 50 MG TABLET,28080840,23139,20140624,0,,0,1970-01-01 00:00:00.020140624
1560170,1130683,464322,2014180,17104,20140629,K4759,7.20,591320205,20.0,5,F,22,HYDROCODON-ACETAMINOPHEN 5-325,28080799,47430,20140629,0,,0,1970-01-01 00:00:00.020140629
1560171,1130821,463893,2014176,17100,20140625,K8463,12.87,406036601,20.0,5,F,16,HYDROCODON-ACETAMINOPH 7.5-325,28080798,47431,20140625,0,,0,1970-01-01 00:00:00.020140625
1560172,1130904,145926,2014178,17102,20140627,M7544,7.40,121050416,60.0,15,F,9,ACETAMINOP-CODEINE 120-12 MG/5,28080883,45154,20140627,0,,0,1970-01-01 00:00:00.020140627
1560173,1131288,465685,2014178,17102,20140627,PA050,8.19,406036701,30.0,4,F,54,HYDROCODON-ACETAMINOPHN 10-325,28080825,30623,20140627,0,,0,1970-01-01 00:00:00.020140627

In [194]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560174 entries, 0 to 1560173
Data columns (total 17 columns):
DE_ID         1560174 non-null int64
VENDOR        1560174 non-null object
DISP_DATE     1560174 non-null int64
SDATE         1560174 non-null int64
Date          1560174 non-null int64
PRESCRIBER    1492174 non-null object
AMT_PAID      1560174 non-null float64
NDC           1560174 non-null int64
QTY           1560174 non-null float64
DAYS          1560174 non-null int64
GENDER        1560174 non-null object
AGE           1560174 non-null int64
LN            1560174 non-null object
AHFS          1560174 non-null object
GCN_SEQNO     1560174 non-null object
var           1560174 non-null int64
Month         1560174 non-null int64
dtypes: float64(2), int64(9), object(6)
memory usage: 202.4+ MB